### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by brunosan** [InfoAmazonia/infoamazonia-wptheme#1]
I´m trying to install this theme, but I´m having problems.
- I´m using Wordpress 3.5.1
- I´ve installed [MapPress plugin](http://wphostreviews.com/mappress-documentation), as requested by the first time install error

I then Install this theme using a .zip file of the root of this repository, but I fails with a missing parent theme error.

`The parent theme is missing. Please install the "mappress" parent theme.`

Any instructions on how to install this would be great. Thanks!!

**Comment by miguelpeixe** [comment]
Hey @brunosan,

You are going for the wrong MapPress. InfoAmazonia is a child theme of a new (yet to be published) parent theme called MapPress. You can [find it on GitHub here](http://github.com/cardume/mappress/).

You need to first install mappress on your themes directory, then infoamazonia and after activate the InfoAmazonia theme.

I strongly recommend you to keep track of MapPress development. This month we'll invest time to release the first stable release.

Cheers

**Comment by brunosan** [comment]
Thanks! Got it.

I´ve installed the theme, but when I activate it, the site renders blank (only a basic header). Any other setup or dependency?
http://smegainmx.bitnamiapp.com/

Thanks!!!

**Comment by MarcosBerger** [comment]
Hello, everbody!
I think I solved this issue. In the "style.css", just replace "jeo" to "jeo-dev" - or the name of the template-master.

/*
Theme Name: InfoAmazonia
Theme URI: http://infoamazonia.org/
Author: memeLab
Author URI: http://www.memelab.com.br/
Description: MapBox maps fully integrated with WodPress with geolocated news and collaboration system
Template: jeo **_(**_HERE: "jeo" to "jeo-dev")**************
Version: 0.0.1
License: GNU General Public License v2 or later
License URI: http://www.gnu.org/licenses/gpl-2.0.html
*/

It should be work!
